DROP TABLE IF EXISTS RECYCLE_STATS;
CREATE TABLE RECYCLE_STATS (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  app_server VARCHAR(255),
  status VARCHAR(255)
);


INSERT INTO RECYCLE_STATS(app_server, status)
values ('gdcul1345','START')
;

